Add all account
adevinta/graph-altimeter pull request #20
Opened 2022-05-02 13:41 UTC by manelmontilla

This PR modifies the prostprocess logic so it adds the account id to all the nodes produced by an Altimeter scan.
Note that this PR depends on the PR:
https://github.com/adevinta/graph-altimeter/pull/19

2022-05-02 14:34 UTC, jroimartin requested changes
LGTM. Just a tiny typo.

2022-05-02 14:34 UTC, jroimartin commented on graph_altimeter/scan/postprocess.py
> +    dictionary"""
Missing trailing dot.

2022-05-02 16:15 UTC, manelmontilla commented on graph_altimeter/scan/postprocess.py
> +    dictionary"""
True thank you.

2022-05-03 09:21 UTC, jroimartin approved these changes
LGTM

2022-05-03 10:25 UTC, merged