remove Altimeter temp files
adevinta/graph-altimeter pull request #27
Opened 2022-05-11 15:37 UTC by manelmontilla

2022-05-14 11:46 UTC, jroimartin requested changes

2022-05-14 11:46 UTC, jroimartin commented on graph_altimeter/scan/__init__.py
> +    performming scan."""
s/performming scan/perfor**m**ing **a** scan/ ?

2022-05-16 07:51 UTC, manelmontilla commented on graph_altimeter/scan/__init__.py
> +    performming scan."""
yep 👍

2022-05-16 09:46 UTC, jroimartin approved these changes
LGTM

2022-05-24 08:38 UTC, merged